def pbPalletGeneralStoreA
	  pbPokemonMart([
      :PUPPETORB,:GREATORB,:ULTRAORB,:MOONBALL,
      :POTION,:SUPERPOTION,:HYPERPOTION,:SAKE,:BEER,:ONIKILLERSAKE,
      :REVIVE,:MAXREVIVE,
      :FULLHEAL,:FULLRESTORE,
      :ETHER,:MAXETHER,:ELIXIR,:MAXELIXIR,
      :REPEL,:SUPERREPEL,:MAXREPEL,
      :PPUP,:RARECANDY,
      :POWERSHARD,:DEFENSESHARD,:TECHSHARD,
      :SWIFTSHARD,:SUPPORTSHARD,:SOLARSHARD,
      :CHROMESHARD
    ], useCat: true)
end

def pbPalletGeneralStoreB
	  pbPokemonMart([
      :PUPPETORB,:GREATORB,:ULTRAORB,:MOONBALL,
      :POTION,:SUPERPOTION,:HYPERPOTION,:SAKE,:BEER,:ONIKILLERSAKE,
      :REVIVE,:MAXREVIVE,
      :FULLHEAL,:FULLRESTORE,
      :ETHER,:MAXETHER,:ELIXIR,:MAXELIXIR,
      :REPEL,:SUPERREPEL,:MAXREPEL,
      :PPUP,:RARECANDY,
      :POWERSHARD,:DEFENSESHARD,:TECHSHARD,
      :SWIFTSHARD,:SUPPORTSHARD,:SOLARSHARD,
      :CHROMESHARD
    ], useCat: true)
end

def pbPalletGeneralStoreC
	  pbPokemonMart([
      :PUPPETORB,:GREATORB,:ULTRAORB,:MOONBALL,
      :POTION,:SUPERPOTION,:HYPERPOTION,:SAKE,:BEER,:ONIKILLERSAKE,
      :REVIVE,:MAXREVIVE,
      :FULLHEAL,:FULLRESTORE,
      :ETHER,:MAXETHER,:ELIXIR,:MAXELIXIR,
      :REPEL,:SUPERREPEL,:MAXREPEL,
      :PPUP,:RARECANDY,
      :POWERSHARD,:DEFENSESHARD,:TECHSHARD,
      :SWIFTSHARD,:SUPPORTSHARD,:SOLARSHARD,
      :CHROMESHARD
    ], useCat: true)
end