  def pbEnemyItemToUse(idxBattler)
      xItems = {
      :XATTACK    => [:ATTACK, (Settings::X_STAT_ITEMS_RAISE_BY_TWO_STAGES) ? 2 : 1],
      :XATTACK2   => [:ATTACK, 2],
      :XATTACK3   => [:ATTACK, 3],
      :XATTACK6   => [:ATTACK, 6],
      :XDEFENSE   => [:DEFENSE, (Settings::X_STAT_ITEMS_RAISE_BY_TWO_STAGES) ? 2 : 1],
      :XDEFENSE2  => [:DEFENSE, 2],
      :XDEFENSE3  => [:DEFENSE, 3],
      :XDEFENSE6  => [:DEFENSE, 6],
      :XDEFEND    => [:DEFENSE, (Settings::X_STAT_ITEMS_RAISE_BY_TWO_STAGES) ? 2 : 1],
      :XDEFEND2   => [:DEFENSE, 2],
      :XDEFEND3   => [:DEFENSE, 3],
      :XDEFEND6   => [:DEFENSE, 6],
      :XSPATK     => [:SPECIAL_ATTACK, (Settings::X_STAT_ITEMS_RAISE_BY_TWO_STAGES) ? 2 : 1],
      :XSPATK2    => [:SPECIAL_ATTACK, 2],
      :XSPATK3    => [:SPECIAL_ATTACK, 3],
      :XSPATK6    => [:SPECIAL_ATTACK, 6],
      :XSPECIAL   => [:SPECIAL_ATTACK, (Settings::X_STAT_ITEMS_RAISE_BY_TWO_STAGES) ? 2 : 1],
      :XSPECIAL2  => [:SPECIAL_ATTACK, 2],
      :XSPECIAL3  => [:SPECIAL_ATTACK, 3],
      :XSPECIAL6  => [:SPECIAL_ATTACK, 6],
      :XSPDEF     => [:SPECIAL_DEFENSE, (Settings::X_STAT_ITEMS_RAISE_BY_TWO_STAGES) ? 2 : 1],
      :XSPDEF2    => [:SPECIAL_DEFENSE, 2],
      :XSPDEF3    => [:SPECIAL_DEFENSE, 3],
      :XSPDEF6    => [:SPECIAL_DEFENSE, 6],
      :XSPEED     => [:SPEED, (Settings::X_STAT_ITEMS_RAISE_BY_TWO_STAGES) ? 2 : 1],
      :XSPEED2    => [:SPEED, 2],
      :XSPEED3    => [:SPEED, 3],
      :XSPEED6    => [:SPEED, 6],
      :XACCURACY  => [:ACCURACY, (Settings::X_STAT_ITEMS_RAISE_BY_TWO_STAGES) ? 2 : 1],
      :XACCURACY2 => [:ACCURACY, 2],
      :XACCURACY3 => [:ACCURACY, 3],
      :XACCURACY6 => [:ACCURACY, 6],
	  :KAPPAATTACK		=> [:ATTACK, 1, :SPECIAL_ATTACK, 1, :SPEED, 1],
	  :KAPPADEFENSE		=> [:DEFENSE, 1, :SPECIAL_DEFENSE, 1, :EVASION, 1]
    }
end